name: 'Install workspace'
description: 'Installs workspace and builds the project'

runs:
  using: "composite"
  steps:
    - name: Install node-js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'

    -  name: Install pnpm
       uses: pnpm/action-setup@v4

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build
      run: pnpm build
      shell: bash