name: deploy_docs

on:
  workflow_dispatch:

jobs:
  publish:
    name: deploy_docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install workspace
        uses: ./.github/actions/install

      - name: Copy Docs Site
        run: mv packages/docs/dist gh-pages
        shell: bash

      - name: Copy Examples Assets
        run: cp packages/demo/.build/client/assets/* gh-pages/assets
        shell: bash

      - name: Copy Examples Pages
        run: cp -R packages/demo/.build/client/use-scroll-position/* gh-pages
        shell: bash

      - name: Set git credentials
        run: |
          git config user.name "n8tb1t"
          git config user.email "n8tb1t@gmail.com"
          git remote set-url origin "https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          REPO_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
